/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sphere.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Sphere(props) {
  const { nodes, materials } = useGLTF('/sphere-transformed.glb')

  materials.glass.iridescence = 1.0
  materials.glass.iridescenceIOR = 1.96
  // materials.glass.iridescenceThicknessRange = [100, 1000]

  materials.glass.thickness = 0.05
  materials.glass.ior = 1.4
  materials.glass.side = THREE.DoubleSide
  materials.glass.roughness = 0.2
  materials.glass.clearcoat = 1.9
  materials.glass.metalness = 0.5

  return (
    <Float rotationIntensity={10} floatIntensity={10}>
      <group {...props} dispose={null}>
        <mesh geometry={nodes.glass.geometry} material={materials.glass} scale={3.79} />
        <mesh geometry={nodes.metal.geometry} material={materials['Material.001']} scale={3.79} />
      </group>
    </Float>
  )
}

useGLTF.preload('/sphere-transformed.glb')
